"""Map layouts (original designs), written as ASCII.

Most maps are drawn as a left half (mirror='h') or top-left quarter
(mirror='hv') and mirrored, so both sides are equally fair.

Legend (per map, `floors`/`walls` say which materials the letters mean):
  .  floor A     ,  floor B     ;  floor C     :  floor D
  #  wall A      %  wall B      &  wall C
  x  void (nothing; blocks walking, bullets fly over)
  w  water (blocks walking, bullets fly over)
  c  crate   o  pillar   b/B/y  barrel red/blue/yellow   t  tree   p  plant
  v  vending machine     u  dumpster      (solid, single tile each)
  d  desk   s  sandbags  n  bench           (multi-tile, low: shoot over them)
  K/L/M  car red/blue/white   T  tank   m  machine   (multi-tile, solid)
  S  spawn point
  1-9  weapon pickup (1 bat 2 glock 3 shotgun 4 ak47 5 chaingun 6 chainsaw
       7 flamethrower 8 katana 9 laser sword)   !  railgun   @  sledgehammer
       $  tesla helmet
Spawn/weapon/prop cells use the floor of the nearest floor neighbour.
"""

MAPS = [
    dict(file='asphaltstreets.dat', name='Asphalt Streets', mirror='h',
         floors=dict(A='asphalt', B='sidewalk', C='asphalt_v', D='cross_h'), walls=dict(A='roof', B='brick'),
         rows=[
             '###############',
             '#S,,,,,,,,,,;.',
             '#,###,,%%%%,;.',
             '#,###,,%%%%,;.',
             '#,###,,%%%%,;2',
             '#,,,,,,,,,,,;.',
             '#..........c::',
             '#.K....L...c..',
             '#.K....L......',
             '#..........S..',
             '#,,,,,,,,,,,;.',
             '#,##,u,,,,,,;.',
             '#,##,,,%%%%,;.',
             '#,##,,,%%%%,;4',
             '#,##,,,%%%%,;.',
             '#S,,,,,,,,,,;.',
             '#..1.......:..',
             '#.....M.......',
             '#.....M....b..',
             '#,,,,,,,,,,,;.',
             '#,%%%%,,###,;.',
             '#,%%%%,,###,;.',
             '#S,,,,,,,,,,;3',
             '###############',
         ]),
    dict(file='officefloor.dat', name='Office Floor', mirror='h',
         floors=dict(A='carpet_blue', B='carpet_red', C='labtile'), walls=dict(A='concrete', B='cubicle'),
         rows=[
             '###############',
             '#S.....%.......',
             '#.dd...%..dd...',
             '#......%.......',
             '#%%%%..%%%..%%%',
             '#.......,,,,,,,',
             '#..p....,,,,,,,',
             '#..2....,,S,,,,',
             '##.###..,,,,,,,',
             '#;;;;#..%%%..##',
             '#;vv;#..%dd....',
             '#;;;;...%......',
             '#;;;;#..%..4...',
             '######..%%%%%..',
             '#S......,,,,,,,',
             '#.dd....,,,,,,,',
             '#.......,,,,8,,',
             '#%%%%...%%%%%..',
             '#.......%......',
             '#.dd..p.%.dd...',
             '#S......%.....3',
             '###############',
         ]),
    dict(file='stormchannel.dat', name='Storm Channel', mirror='h',
         floors=dict(A='concrete', B='grate'), walls=dict(A='concrete', B='metal'),
         rows=[
             '###############',
             '#S........#...',
             '#.........#.4.',
             '#..c......#...',
             '#....%%...#...',
             '#....%%.......',
             '#.............',
             '#wwwwwww,,wwww',
             '#wwwwwww,,wwww',
             '#....1........',
             '#.............',
             '#.%%....#..S..',
             '#.%%....#.....',
             '#.......#..b..',
             '#wwww,,wwwwwww',
             '#wwww,,wwwwwww',
             '#..........c..',
             '#S......@.....',
             '#....##.......',
             '#..........#3.',
             '###############',
         ]),
    dict(file='trailerpark.dat', name='Trailer Park', mirror='h',
         floors=dict(A='sand', B='dirt', C='gravel'), walls=dict(A='trailer', B='hedge'),
         rows=[
             '###############',
             '#S.....;;;;;;;',
             '#.###..;;;;;;;',
             '#.###..;;K;;;;',
             '#.###..;;K;;2;',
             '#......;;;;;;;',
             '#...t.........',
             '#......,,,,,..',
             '#.###..,,,,,..',
             '#.###..,,u,,.S',
             '#.###..,,,,,..',
             '#......,,,,,..',
             '#..1..........',
             '#%%%%...t.....',
             '#.......###...',
             '#..s....###.5.',
             '#..s....###...',
             '#S............',
             '###############',
         ]),
    dict(file='orbitstation.dat', name='Orbit Station', mirror='hv',
         floors=dict(A='metal', B='grate'), walls=dict(A='metal'),
         rows=[
             'xxxxxxxxxxxxxxx',
             'x#####xxxxxxxxx',
             'x#S..#xxxxxxxxx',
             'x#.8.,,,,,,,,,,',
             'x#..m#xxxxxxx,x',
             'x#..m#xxxxxxx,x',
             'x##,##xxxxxxx,x',
             'xxx,xxxxx####.#',
             'xxx,xxxxx#....#',
             'xxx,xxxxx#.5..,',
             'xxx,,,,,,,..o..',
             'xxxxxxxxx#....#',
             'xxxxxxxxx##.###',
         ]),
    dict(file='biolab.dat', name='Bio Lab', mirror='h',
         floors=dict(A='labtile', B='metal'), walls=dict(A='concrete', B='metal'),
         rows=[
             '###############',
             '#S....#.......',
             '#.TT..#..p....',
             '#.TT..#.......',
             '#.....###%%%..',
             '#.............',
             '#...,,,,,,,...',
             '#%%%,,m,,,,%%%',
             '#...,,m,,!,...',
             '#...,,,,,,,...',
             '#......9......',
             '#..###....###.',
             '#..#S......$#.',
             '#..#.........',
             '#..####..####.',
             '#.....TT......',
             '#..p..TT....v.',
             '#S............',
             '###############',
         ]),
    dict(file='containerport.dat', name='Container Port', mirror='h',
         floors=dict(A='concrete', B='asphalt'), walls=dict(A='concrete', B='container_blue', C='container_red'),
         rows=[
             '###############',
             '#S...........',
             '#.&&&&..%%%%..',
             '#.&&&&..%%%%..',
             '#.........c...',
             '#,,,,,,,,,,,,,',
             '#,%%%%,,,,&&&&',
             '#,%%%%,,4,&&&&',
             '#,,,,,,,,,,,,,',
             '#..cc.....S...',
             '#..cc..b......',
             '#.&&&&...%%%%.',
             '#.&&&&...%%%%.',
             '#........6....',
             '#wwwwwwwwwwwww',
             '###############',
         ]),
    dict(file='thepitarena.dat', name='The Pit Arena', mirror='hv',
         floors=dict(A='stone', B='sand'), walls=dict(A='stone'),
         rows=[
             '###############',
             '#S..........o.',
             '#.,,,,,,,,,,,,',
             '#.,o,,,2,,,,,,',
             '#.,,,....,,,,,',
             '#.,,.....,,,,,',
             '#..,,..S.,,xxx',
             '#..,,....,xxxx',
             '#.,,,,4,,xxxxx',
             '#.,,,,,,,xxxxx',
             '#o,,,,,@,xxxxx',
         ]),
    dict(file='hedgemaze.dat', name='Hedge Maze', mirror='hv',
         floors=dict(A='grass', B='dirt'), walls=dict(A='hedge'),
         rows=[
             '###############',
             '#S....#.......',
             '#.###.#.#####.',
             '#.#...........',
             '#.#.###.,,,#.#',
             '#...#t..,8,#..',
             '###.#...,,,#.#',
             '#......#.....,',
             '#.####.#.###.,',
             '#.#2.........,',
             '#.#.#t#.,,,,,,',
         ]),
    dict(file='shipyard.dat', name='Shipyard', mirror='h',
         floors=dict(A='wood', B='concrete'), walls=dict(A='metal'),
         rows=[
             '###############',
             '#S,,,,,,,,,,,,,',
             '#,,c,,,,b,,,,,,',
             '#,,c,,,,,,,,,,,',
             '#,,,,,,,,,####,',
             '#,,7,,,,,,####,',
             '#wwww....wwwwww',
             '#wwww....wwwwww',
             '#ww..........ww',
             '#ww....S.....ww',
             '#ww..c.......3.',
             '#wwwww...wwwwww',
             '#,,,,,...,,,,,,',
             '#,S,,,,,,,,,,,,',
             '#,,,,,,c,,,c,,,',
             '###############',
         ]),
    dict(file='foundry.dat', name='Foundry', mirror='h',
         floors=dict(A='metal', B='concrete', C='grate'), walls=dict(A='metal', B='brick'),
         rows=[
             '###############',
             '#S...........',
             '#.mm...mm....',
             '#.mm...mm..5.',
             '#............',
             '#%%%%..%%%%;;;',
             '#,,,,..,,,,;;;',
             '#,,,,..,,,,;;;',
             '#,,S,..,,6,;;;',
             '#%%%%..%%%%;;;',
             '#.............',
             '#..y.....mm...',
             '#..y.....mm...',
             '#S......@.....',
             '###############',
         ]),
    dict(file='sandbase.dat', name='Sand Base', mirror='h',
         floors=dict(A='sand', B='concrete'), walls=dict(A='concrete'),
         rows=[
             '###############',
             '#S............',
             '#..sss....ss..',
             '#.............',
             '#.#####..,,,,,',
             '#.#,,,#..,,,,,',
             '#.#,4,...,,!,,',
             '#.#,,,#..,,,,,',
             '#.##.##..,,,,,',
             '#.............',
             '#...ss....S...',
             '#........sss..',
             '#.###.........',
             '#.#3......y...',
             '#S#...........',
             '###############',
         ]),
    dict(file='stonekeep.dat', name='Stone Keep', mirror='hv',
         floors=dict(A='stone', B='grass'), walls=dict(A='stone'),
         rows=[
             '###############',
             '#S,,,,,,t,,,,,',
             '#,,,,,,,,,,,,,',
             '#,,####..####.',
             '#,,#........#.',
             '#,,#.S......#.',
             '#,t#..###...#.',
             '#,,...#8....',
             '#,,#..#.....7.',
             '#,,#.........',
         ]),
    dict(file='rooftops.dat', name='Rooftops', mirror='h',
         floors=dict(A='gravel', B='metal', C='wood'), walls=dict(A='brick'),
         rows=[
             'xxxxxxxxxxxxxxx',
             'x#######xxxxxxx',
             'x#S....#xx#####',
             'x#..m..#xx#...',
             'x#.....;;;;.2.',
             'x#..o..#xx#...',
             'x###.###xx#..S',
             'xxx;xxxxxx##.#',
             'xxx;xxxxxxxx;x',
             'x###.#####xx;x',
             'x#.......#xx;x',
             'x#..S..1.;;;;;',
             'x#..m....#xxxx',
             'x#.......#xxxx',
             'x#########xxxx',
             'xxxxxxxxxxxxxxx',
         ]),
    dict(file='metroline.dat', name='Metro Line', mirror='h',
         floors=dict(A='concrete', B='track', C='labtile'), walls=dict(A='concrete'),
         rows=[
             '###############',
             '#S...o....o...',
             '#.............',
             '#..n.....n..4.',
             '#.............',
             '#,,,,,,,,,,,,,',
             '#,,,,,,,,,,,,,',
             '#...;;;;;;....',
             '#..o;;S;;;o..2',
             '#...;;;;;;....',
             '#,,,,,,,,,,,,,',
             '#,,,,,,,,,,,,,',
             '#.............',
             '#..n..v..n..9.',
             '#S...o....o...',
             '###############',
         ]),
]

DEBUG_MAP = dict(file='debug.dat', name='Test Room', mirror=None,
                 floors=dict(A='labtile', B='metal'), walls=dict(A='concrete'),
                 rows=[
                     '############',
                     '#S........S#',
                     '#.,,,..,,,.#',
                     '#.,1,..,2,.#',
                     '#.,,,..,,,.#',
                     '#....##....#',
                     '#....##....#',
                     '#.,,,..,,,.#',
                     '#.,3,..,4,.#',
                     '#.,,,..,,,.#',
                     '#S........S#',
                     '############',
                 ])
